INSERT INTO Organisms (alias,dans_bigscape,Full_Name,Genus,Espece,Genre_espece,taxo_id,Taxo_Clade) VALUES
	 ('Abobie1',1,'Abortiporus biennis ​CIRM-BRFM 1778 v1.0','Abortiporus','biennis','Abortiporus biennis',1,'Residual Polyporoid'),
	 ('Acrchr1',1,'Acremonium chrysogenum ATCC 11550','Acremonium','chrysogenum','Acremonium chrysogenum',2,'NA'),
	 ('Amylap1',1,'Amylocystis lapponica SKaAmylap13 v1.0','Amylocystis','lapponica','Amylocystis lapponica',3,'Antrodia'),
	 ('Antser1',1,'Antrodia serialis Sig1Antser10 v1.0','Antrodia','serialis','Antrodia serialis',4,'Antrodia'),
	 ('Artele1122',1,'Artolenzites elegans CIRM-BRFM 1122 v1.0','Artolenzites','elegans','Artolenzites elegans',5,'Core Polyporoid'),
	 ('Bjead1',1,'Bjerkandera adusta v1.0','Bjerkandera','adusta','Bjerkandera adusta',6,'Phlebioid'),
	 ('Cersu1',0,'Ceriporiopsis (Gelatoporia) subvermispora B','Ceriporiopsis','subvermispora','Ceriporiopsis subvermispora',7,'Gelatoporia'),
	 ('Cytmel1',1,'Cytidiella melzeri FP 102339 v1.0','Cytidiella','melzeri','Cytidiella melzeri',7,'Phlebioid'),
	 ('Daequ1',1,'Daedalea quercina v1.0','Daedalea','quercina','Daedalea quercina',4,'Antrodia'),
	 ('Dicsq1',1,'Dichomitus squalens LYAD-421 SS1 v1.0','Dichomitus','squalens','Dichomitus squalens',5,'Core Polyporoid'),
	 ('Dicsqu18370',1,'Dichomitus squalens OM18370.1 v1.0','Dichomitus','squalens','Dichomitus squalens',5,'Core Polyporoid'),
	 ('Dicsqu463',1,'Dichomitus squalens CBS463.89 v1.0','Dichomitus','squalens','Dichomitus squalens',5,'Core Polyporoid'),
	 ('Dicsqu464',1,'Dichomitus squalens CBS464.89 v1.0','Dichomitus','squalens','Dichomitus squalens',5,'Core Polyporoid'),
	 ('Earsca1',1,'Earliella scabrosa CIRM-BRFM 1817 v1.0','Earliella','scabrosa','Earliella scabrosa',5,'Core Polyporoid'),
	 ('Epityp1',1,'Epithele typhae CBS 203.58 v1.0','Epithele','typhae','Epithele typhae',5,'Core Polyporoid'),
	 ('Fibra1',1,'Fibroporia radiculosa TFFH 294','Fibroporia','radiculosa','Fibroporia radiculosa',8,'Antrodia'),
	 ('Fomfom1',1,'Fomes fomentarius CIRM-BRFM 1821 v1.0','Fomes','fomentarius','Fomes fomentarius',5,'Core Polyporoid'),
	 ('Fompi3',0,'Fomitopsis schrenkii FP-58527 SS1 v3.0','Fomitopsis','schrenkii','Fomitopsis schrenkii',4,'Antrodia'),
	 ('Fomros1',1,'Rhodofomes roseus CIRM-BRFM 1785 v1.0','Rhodofomes','roseus','Rhodofomes roseus',4,'Antrodia'),
	 ('Ganbon1',0,'Ganoderma boninense G3 v1.0','Ganoderma','boninense','Ganoderma boninense',5,'Core Polyporoid'),
	 ('Ganleu1',1,'Ganoderma leucocontextum Dai12418 v1.0','Ganoderma','leucocontextum','Ganoderma leucocontextum',5,'Core Polyporoid'),
	 ('Ganluc1',0,'Ganoderma lucidum G.260125-1 v1.0','Ganoderma','lucidum','Ganoderma lucidum',5,'Core Polyporoid'),
	 ('Gansi1',0,'Ganoderma sinense ZZ0214-1','Ganoderma','sinense','Ganoderma sinense',5,'Core Polyporoid'),
	 ('Gansp1',1,'Ganoderma sp. 10597 SS1 v1.0','Ganoderma','sp.','Ganoderma sp.',5,'Core Polyporoid'),
	 ('Hexnit1',1,'Hexagonia nitida CIRM-BRFM 1802 v1.0','Hexagonia','nitida','Hexagonia nitida',5,'Core Polyporoid'),
	 ('Hydfim1',1,'Hydnopolyporus fimbriatus CBS384.51 v1.0','Hydnopolyporus','fimbriatus','Hydnopolyporus fimbriatus',9,'Phlebioid'),
	 ('Irplac1',1,'Irpex lacteus CCBAS Fr. 238 617/93 v1.0','Irpex','lacteus','Irpex lacteus',9,'Phlebioid'),
	 ('Laesu1',1,'Laetiporus sulphureus var. sulphureus v1.0','Laetiporus','sulphureus','Laetiporus sulphureus',10,'Antrodia'),
	 ('Leisp1',0,'Leiotrametes sp. CIRM-BRFM 1775 v1.0','Leiotrametes','sp.','Leiotrametes sp.',5,'Core Polyporoid'),
	 ('Lenti6',1,'Lentinus tigrinus ALCF2SS1-6 v1.0','Lentinus','tigrinus','Lentinus tigrinus',5,'Core Polyporoid'),
	 ('Lenti7',1,'Lentinus tigrinus ALCF2SS1-7 v1.0','Lentinus','tigrinus','Lentinus tigrinus',5,'Core Polyporoid'),
	 ('Obbri1',1,'Obba rivulosa 3A-2 v1.0','Obba','rivulosa','Obba rivulosa',11,'Gelatoporia'),
	 ('Panru1',0,'Panus rudis PR-1116 ss-1 v1.0','Panus','rudis','Panus rudis',12,'Residual Polyporoid'),
	 ('Pengri1',1,'Penicillium griseofulvum PG3','Penicillium','griseofulvum','Penicillium griseofulvum',13,'NA'),
	 ('Phaca1',1,'Phanerochaete carnosa HHB-10118-Sp v1.0','Phanerochaete','carnosa','Phanerochaete carnosa',6,'Phlebioid'),
	 ('Phchr2',1,'Phanerochaete chrysosporium RP-78 v2.2','Phanerochaete','chrysosporium','Phanerochaete chrysosporium',6,'Phlebioid'),
	 ('Phlbr1',1,'Phlebia brevispora HHB-7030 SS6 v1.0','Phlebia','brevispora','Phlebia brevispora',7,'Phlebioid'),
	 ('Phlcen1',1,'Phlebia centrifuga FBCC195 ','Phlebia','centrifuga','Phlebia centrifuga',7,'Phlebioid'),
	 ('Phlgi1',0,'Phlebiopsis gigantea v1.0','Phlebiopsis','gigantea','Phlebiopsis gigantea',6,'Phlebioid'),
	 ('Phlrad1',1,'Phlebia radiata Fr. (isolate 79, FBCC0043)','Phlebia','radiata','Phlebia radiata',7,'Phlebioid'),
	 ('Pipbet1_1',0,'Fomitopsis betulina CIRM-BRFM 1772 v1.1','Fomitopsis','betulina','Fomitopsis betulina',4,'Antrodia'),
	 ('Polar1',1,'Polyporus arcularius v1.0','Polyporus','arcularius','Polyporus arcularius',5,'Core Polyporoid'),
	 ('Polbr1',0,'Polyporus brumalis CIRM-BRFM 1820 v1.0','Polyporus','brumalis','Polyporus brumalis',5,'Core Polyporoid'),
	 ('Polsqu1',1,'Polyporus squamosus CCBS 676 v1.0','Polyporus','squamosus','Polyporus squamosus',5,'Core Polyporoid'),
	 ('Porspa1',1,'Porosterum spadiceum BS34 v1.0','Porostereum','spadiceum','Porostereum spadiceum',6,'Phlebioid'),
	 ('Pospl1',0,'Postia placenta MAD 698-R v1.0','Postia','placenta','Postia placenta',3,'Antrodia'),
	 ('PosplRSB12',1,'Postia placenta MAD-698-R-SB12 v1.0','Postia','placenta','Postia placenta',3,'Antrodia'),
	 ('Pycci1',0,'Pycnoporus cinnabarinus CIRM-BRFM 137 v1.0','Pycnoporus','cinnabarinus','Pycnoporus cinnabarinus',5,'Core Polyporoid'),
	 ('Pycco1',1,'Pycnoporus coccineus CIRM-BRFM 310 v1.0','Pycnoporus','coccineus','Pycnoporus coccineus',5,'Core Polyporoid'),
	 ('Pycpun1',1,'Pycnoporus puniceus CIRM-BRFM 1868 v1.0','Pycnoporus','puniceus','Pycnoporus puniceus',5,'Core Polyporoid'),
	 ('Pycsa1',0,'Pycnoporus sanguineus CIRM-BRFM 1264 v1.0','Pycnoporus','sanguineus','Pycnoporus sanguineus',5,'Core Polyporoid'),
	 ('Rigmic1',1,'Rigidoporus microporus ED310 v1.0','Rigidoporus','microporus','Rigidoporus microporus',14,'Residual Polyporoid'),
	 ('Trabet1',1,'Trametes betulina CIRM-BRFM 1801 v1.0','Trametes','betulina','Trametes betulina',5,'Core Polyporoid'),
	 ('Trace1',0,'Trametopsis cervina CIRM-BRFM 1824 v1.0','Trametopsis','cervina','Trametopsis cervina',9,'Phlebioid'),
	 ('Traci1',0,'Trametes cingulata CIRM-BRFM 1805 v1.0','Trametes','cingulata','Trametes cingulata',5,'Core Polyporoid'),
	 ('Tragib1',1,'Trametes gibbosa CIRM-BRFM 1770 v1.0','Trametes','gibbosa','Trametes gibbosa',5,'Core Polyporoid'),
	 ('Tralac1',1,'Leiotrametes lactinea CIRM-BRFM 1664 v1.0','Leiotrametes','lactinea','Leiotrametes lactinea',5,'Core Polyporoid'),
	 ('Tralj1',1,'Trametes ljubarskyi CIRM-BRFM 1659 v1.0','Trametes','ljubarskyi','Trametes ljubarskyi',5,'Core Polyporoid'),
	 ('Tramax1',1,'Trametes maxima CIRM-BRFM 1813 v1.0','Trametes','maxima','Trametes maxima',5,'Core Polyporoid'),
	 ('Tramen1',1,'Leiotrametes menziesii CIRM-BRFM 1781 v1.0','Leiotrametes','menziesii','Leiotrametes menziesii',5,'Core Polyporoid'),
	 ('Tramey1',0,'Trametes meyenii CIRM-BRFM 1810 v1.0','Trametes','meyenii','Trametes meyenii',5,'Core Polyporoid'),
	 ('Trapol1',1,'Trametes polyzona CIRM-BRFM 1798 v1.0','Trametes','polyzona','Trametes polyzona',5,'Core Polyporoid'),
	 ('Trapub1',1,'Trametes pubescens FBCC735','Trametes','pubescens','Trametes pubescens',5,'Core Polyporoid'),
	 ('Trave1',1,'Trametes versicolor v1.0','Trametes','versicolor','Trametes versicolor',5,'Core Polyporoid'),
	 ('Traver1',1,'Trametes versicolor ATCC 20869','Trametes','versicolor','Trametes versicolor',5,'Core Polyporoid'),
	 ('Wolco1',0,'Wolfiporia cocos MD-104 SS10 v1.0','Wolfiporia','cocos','Wolfiporia cocos',4,'Antrodia');


INSERT INTO Taxonomy (Taxo_Fam,Taxo_Order,Taxo_Class,Taxo_Phylum) VALUES
	 ('Podoscyphaceae','Polyporales','Agaricomycetes','Basidiomycota'),
	 ('Hypocreaceae','Not assigned','Sordariomycetes','Ascomycota'),
	 ('Dacryobolaceae','Polyporales','Agaricomycetes','Basidiomycota'),
	 ('Fomitopsidaceae','Polyporales','Agaricomycetes','Basidiomycota'),
	 ('Polyporaceae','Polyporales','Agaricomycetes','Basidiomycota'),
	 ('Phanerochaetaceae','Polyporales','Agaricomycetes','Basidiomycota'),
	 ('Meruliaceae','Polyporales','Agaricomycetes','Basidiomycota'),
	 ('Fibroporiaceae','Polyporales','Agaricomycetes','Basidiomycota'),
	 ('Irpicaceae','Polyporales','Agaricomycetes','Basidiomycota'),
	 ('Laetiporaceae','Polyporales','Agaricomycetes','Basidiomycota'),
	 ('Gelatoporiaceae','Polyporales','Agaricomycetes','Basidiomycota'),
	 ('Panaceae','Polyporales','Agaricomycetes','Basidiomycota'),
	 ('Aspergillaceae','Eurotiales','Eurotiomycetes','Ascomycota'),
	 ('Meripilaceae','Polyporales','Agaricomycetes','Basidiomycota');